### ISSUE TITLE
Unable to retrieve the org_id , when having a subdomain 

### ISSUE THREAD

**Issue by bwnyasse** [jasonbisson/gcp_logs_to_splunk#3]
if you are assigned to 2 organizations for example : 
- example.com
- sub.example.com

The second being a subdomain , the script is unable to retrieve the right org_id
your grep command in the following line may retrieve the wrong id.

`export org_id=$(gcloud organizations list --format=[no-heading] | grep ${org_name} | awk '{print $2}')`

**Comment by bwnyasse** [comment]
Hi @jasonbisson  Thank you for the [video](https://www.youtube.com/watch?v=O5tmSHCJNp8&feature=youtu.be) , I propose the following [PR](https://github.com/jasonbisson/gcp_logs_to_splunk/pull/4)

**Comment by jasonbisson** [comment]
Good catch! Sorry, it took so long to fix. I've been moving most of my GCP deployments to declarative approach with Terraform, but I still like the imperative deployments with Bash :)
